project:
  type: website
  output-dir: docs

website:
  title: "."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jgilbe14
      - icon: linkedin
        href: https://www.linkedin.com/in/josiah-gilbert/
format:
  html:
    theme: zephyr
    css: styles.css



